#!/bin/sh

set -e
set -x

#tools/config/generate_sample.sh

DESTIN=debian/cinder-common/usr/share/cinder-common/cinder.conf
sed -i 's/^[ \t#]*enabled_backends[ \t]*=.*/enabled_backends = lvm/' ${DESTIN}

echo "[lvm]
volume_driver = cinder.volume.drivers.lvm.LVMVolumeDriver
volume_group = pkgosvg0
iscsi_protocol = iscsi
iscsi_helper = tgtadm  
" >>${DESTIN}
